import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

    const session = await auth();
    console.log(session);
    
    if(session) {
        redirect("/");
    }
    
  return (
    <>
    {children}
    </>
  );
}
