import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import {Poppins } from "next/font/google";
import RootLayoutWrapper from "@/components/RootLayoutWrapper";

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-inter", // optional but best practice
// });

const inter = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter", // optional but best practice
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="hydrated dark">
      <body className={`${inter.className}`}>
        <RootLayoutWrapper>
          <Navbar />
          {children}
          <Footer />
        </RootLayoutWrapper>
      </body>
    </html>
  );
}
